version: '2'

vars:
  NAME: whitebox-controller
  VERSION: 0.1.0
  COMMIT: {sh: git rev-parse --verify HEAD}
  BUILD_FLAGS: -ldflags "-X main.VERSION={{.VERSION}} -X main.COMMIT={{.COMMIT}}"

tasks:
  build:
    deps: [test]
    cmds:
    - CGO_ENABLED=0 go build {{.BUILD_FLAGS}} ./cmd/whitebox-controller
  test:
    cmds:
    - go vet ./...
    - go test -v -coverprofile=cover.out ./...
  cover:
    deps: [test]
    cmds:
    - go tool cover -html=cover.out
  release:
    deps: [test]
    cmds:
    - mkdir release
    - CGO_ENABLED=0 GOOS=darwin go build {{.BUILD_FLAGS}} ./cmd/whitebox-controller
    - tar zcf release/{{.NAME}}-darwin-amd64.tar.gz whitebox-controller
    - CGO_ENABLED=0 GOOS=linux go build {{.BUILD_FLAGS}} ./cmd/whitebox-controller
    - tar zcf release/{{.NAME}}-linux-amd64.tar.gz whitebox-controller
  github-release:
    deps: [release]
    cmds:
    - ghr v{{.VERSION}} release/
  clean:
    cmds:
    - rm -rf cover.out whitebox-controller release
  build-container:
    cmds:
    - docker build --build-arg BUILD_FLAGS='{{.BUILD_FLAGS}}' -t summerwind/{{.NAME}}:latest -t summerwind/{{.NAME}}:{{.VERSION}} .
  push-container:
    cmds:
    - docker push summerwind/{{.NAME}}:latest
  push-release-container:
    cmds:
    - docker push summerwind/{{.NAME}}:{{.VERSION}}
