version: '2'

vars:
  NAME: whitebox-controller
  VERSION: 0.7.0
  COMMIT: {sh: git rev-parse --verify HEAD}
  BUILD_FLAGS: -ldflags "-X main.VERSION={{.VERSION}} -X main.COMMIT={{.COMMIT}}"

tasks:
  build:
    deps: [test]
    cmds:
    - CGO_ENABLED=0 go build {{.BUILD_FLAGS}} ./cmd/whitebox-controller
    - CGO_ENABLED=0 go build {{.BUILD_FLAGS}} ./cmd/whitebox-gen
  test:
    cmds:
    - go vet ./...
    - go test -v -coverprofile=cover.out ./...
  cover:
    deps: [test]
    cmds:
    - go tool cover -html=cover.out
  release:
    cmds:
    - docker build --build-arg VERSION={{.VERSION}} --build-arg COMMIT={{.COMMIT}} --target release -t summerwind/{{.NAME}}:release .
    - docker create --name {{.NAME}}-release summerwind/{{.NAME}}:release
    - docker cp {{.NAME}}-release:/workspace/release release
    - docker rm {{.NAME}}-release
  github-release:
    deps: [release]
    cmds:
    - ghr v{{.VERSION}} release/
  clean:
    cmds:
    - rm -rf whitebox-controller whitebox-gen cover.out release
  build-container:
    cmds:
    - docker build --build-arg VERSION={{.VERSION}} --build-arg COMMIT={{.COMMIT}} -t summerwind/{{.NAME}}:latest -t summerwind/{{.NAME}}:{{.VERSION}} .
  push-container:
    cmds:
    - docker push summerwind/{{.NAME}}:latest
  push-release-container:
    cmds:
    - docker push summerwind/{{.NAME}}:{{.VERSION}}
