version: '2'

vars:
  NAME: whitebox-controller
  VERSION: 0.1.0
  COMMIT: {sh: git rev-parse --verify HEAD}
  BUILD_FLAGS: -ldflags "-X main.VERSION={{.VERSION}} -X main.COMMIT={{.COMMIT}}"

tasks:
  build:
    deps: [test]
    cmds:
    - CGO_ENABLED=0 go build {{.BUILD_FLAGS}} .
  test:
    cmds:
    - go vet ./...
    - go test -v -coverprofile=cover.out ./...
  cover:
    deps: [test]
    cmds:
    - go tool cover -html=cover.out
  dist:
    deps: [test]
    cmds:
    - mkdir dist
    - CGO_ENABLED=0 GOOS=darwin go build {{.BUILD_FLAGS}} .
    - tar zcf dist/{{.NAME}}-darwin-amd64.tar.gz {{.NAME}}
    - CGO_ENABLED=0 GOOS=linux go build {{.BUILD_FLAGS}} .
    - tar zcf dist/{{.NAME}}-linux-amd64.tar.gz {{.NAME}}
  release:
    deps: [dist]
    cmds:
    - github-release upload -u summerwind -r {{.NAME}} -t v{{.VERSION}} -f dist/{{.NAME}}-darwin-amd64.tar.gz
    - github-release upload -u summerwind -r {{.NAME}} -t v{{.VERSION}} -f dist/{{.NAME}}-linux-amd64.tar.gz
  clean:
    cmds:
    - rm -rf cover.out whitebox-controller dist
  build-container:
    deps: [test]
    cmds:
    - docker build --build-arg BUILD_FLAGS='{{.BUILD_FLAGS}}' -t summerwind/{{.NAME}}:latest -t summerwind/{{.NAME}}:{{.VERSION}} .
  push-container:
    cmds:
    - docker push summerwind/{{.NAME}}:latest
  push-release-container:
    cmds:
    - docker push summerwind/{{.NAME}}:{{.VERSION}}
