apiVersion: v1
kind: ServiceAccount
metadata:
  name: noop-controller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: noop-controller
rules:
- apiGroups:
  - whitebox.summerwind.github.io
  resources:
  - noop
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: noop-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: noop-controller
subjects:
- kind: ServiceAccount
  name: noop-controller
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: noop-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: noop-controller
  template:
    metadata:
      labels:
        app: noop-controller
    spec:
      containers:
      - name: noop-controller
        image: summerwind/noop-controller:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: secret-volume
          mountPath: /etc/tls
        ports:
        - containerPort: 8001
        resources:
          requests:
            cpu: 100m
            memory: 20Mi
      volumes:
      - name: secret-volume
        secret:
          secretName: noop-controller
          items:
          - key: server.pem
            path: server.pem
          - key: server-key.pem
            path: server-key.pem
      serviceAccountName: noop-controller
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: noop-controller
  namespace: kube-system
spec:
  selector:
    app: noop-controller
  ports:
  - protocol: TCP
    port: 443
    targetPort: 8001
