version: 2
jobs:
  build:
    docker:
    - image: summerwind/toolbox:latest
    environment:
      GO111MODULE: "on"
      DOCKER_BUILDKIT: "1"
    steps:
    - checkout
    - setup_remote_docker:
        version: 18.09.3
    - run:
        name: Build container
        command: task build-container
