apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-observer
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-observer
rules:
- apiGroups:
  - ""
  resources:
  - pod
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-observer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-observer
subjects:
- kind: ServiceAccount
  name: pod-observer
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-observer
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-observer
  template:
    metadata:
      labels:
        app: pod-observer
    spec:
      containers:
      - name: pod-observer
        image: summerwind/pod-observer:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 20Mi
      serviceAccountName: pod-observer
