apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: containerset.whitebox.summerwind.dev
spec:
  group: whitebox.summerwind.dev
  versions:
  - name: v1alpha1
    served: true
    storage: true
  names:
    kind: ContainerSet
    plural: containerset
    singular: containerset
  scope: Namespaced
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: containerset-controller-selfsign
  namespace: kube-system
spec:
  selfSigned: {}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: containerset-controller-webhook-ca
  namespace: kube-system
spec:
  secretName: containerset-controller-webhook-ca
  issuerRef:
    name: containerset-controller-selfsign
  commonName: "containerset-controller webhook CA"
  duration: 43800h
  isCA: true
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: containerset-controller-webhook-ca
  namespace: kube-system
spec:
  ca:
    secretName: containerset-controller-webhook-ca
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: containerset-controller
  namespace: kube-system
spec:
  secretName: containerset-controller
  issuerRef:
    name: containerset-controller-webhook-ca
  dnsNames:
  - containerset-controller
  - containerset-controller.kube-system
  - containerset-controller.kube-system.svc
  duration: 8760h
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: containerset-controller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: containerset-controller
rules:
- apiGroups:
  - whitebox.summerwind.dev
  resources:
  - containerset
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: containerset-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: containerset-controller
subjects:
- kind: ServiceAccount
  name: containerset-controller
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: containerset-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: containerset-controller
  template:
    metadata:
      labels:
        app: containerset-controller
    spec:
      containers:
      - name: containerset-controller
        image: summerwind/containerset-controller:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: certificates
          mountPath: /etc/tls
        ports:
        - containerPort: 443
        - containerPort: 8080
      volumes:
      - name: certificates
        secret:
          secretName: containerset-controller
      serviceAccountName: containerset-controller
      terminationGracePeriodSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  name: containerset-controller
  namespace: kube-system
spec:
  selector:
    app: containerset-controller
  ports:
  - protocol: TCP
    port: 443
    targetPort: 443
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: containerset-controller
  annotations:
    certmanager.k8s.io/inject-ca-from: kube-system/containerset-controller
webhooks:
- name: containerset.whitebox.summerwind.dev
  rules:
  - apiGroups:
    - whitebox.summerwind.dev
    apiVersions:
    - v1alpha1
    resources:
    - containerset
    operations:
    - CREATE
    - UPDATE
  failurePolicy: Fail
  clientConfig:
    service:
      name: containerset-controller
      namespace: kube-system
      path: /whitebox.summerwind.dev/v1alpha1/containerset/validate
    caBundle: ""
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: containerset-controller
  annotations:
    certmanager.k8s.io/inject-ca-from: kube-system/containerset-controller
webhooks:
- name: containerset.whitebox.summerwind.dev
  rules:
  - apiGroups:
    - whitebox.summerwind.dev
    apiVersions:
    - v1alpha1
    resources:
    - containerset
    operations:
    - CREATE
    - UPDATE
  failurePolicy: Fail
  clientConfig:
    service:
      name: containerset-controller
      namespace: kube-system
      path: /whitebox.summerwind.dev/v1alpha1/containerset/mutate
    caBundle: ""
