apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: containerset.whitebox.summerwind.github.io
spec:
  group: whitebox.summerwind.github.io
  versions:
  - name: v1alpha1
    served: true
    storage: true
  names:
    kind: ContainerSet
    plural: containerset
    singular: containerset
    shortNames:
    - nop
  scope: Namespaced
